name: 'Run Connect Integration Test'
description: 'Run integration test for a single extension'

inputs:
  extension-name:
    description: 'Name of extension to test'
    required: true
  connect-version:
    description: 'Connect version to test against'
    required: true
  connect-license:
    description: 'Posit Connect license'
    required: true

outputs:
  test_status:
    description: 'Status of the integration test'
    value: ${{ steps.run-test.outputs.status }}
  reports_path:
    description: 'Path to test reports'
    value: ${{ steps.run-test.outputs.reports_path }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    # Here we download the packaged extension artifact created from the calling workflow
    - uses: actions/download-artifact@v4 
      with:
        name: ${{ inputs.extension-name }}.tar.gz
        path: integration/bundles

    - uses: astral-sh/setup-uv@v7
      with:
        pyproject-file: "./integration/pyproject.toml"

    - name: Install isolated Python with UV
      shell: bash
      working-directory: ./integration
      run: uv python install

    - name: Run integration tests
      uses: posit-dev/with-connect@main
      with:
        version: ${{ inputs.connect-version }}
        license: ${{ inputs.connect-license }}
        command: make -C ./integration test-${{ inputs.connect-version }} EXTENSION_NAME=${{ inputs.extension-name }}
