name: Extension Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Detects file changes in extension directories that utilize the `simple-extensions`
  # job below
  simple-extension-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as 'changes' output variable
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          # Adding a new extension that has a directory that can be TARed?
          # Add a new line here with the name of the extension as the name of
          # the filter and the value as the extension's directory path
          # Be sure the extension name and directory name are the same
          # e.g. `extension-name: extensions/extension-name/**`
          filters: |
            champion-dashboard: extensions/champion-dashboard/**

  # Runs for each extension that has changed from `simple-extension-changes`
  # Lints and packages in preparation for integration tests.
  simple-extensions:
    needs: [simple-extension-changes]
    # Will only run if there are changes in the simple extensions
    # https://github.com/dorny/paths-filter/issues/66#issuecomment-778267385
    if: ${{ needs.simple-extension-changes.outputs.changes != '[]' && needs.simple-extension-changes.outputs.changes != '' }}
    strategy:
      # Do not fail fast so all extensions are processed
      fail-fast: false
      matrix:
        # Parse JSON containing names of all filters matching any of changed extensions
        # e.g. ['reaper'] if the reaper extension dir changed
        extension: ${{ fromJSON(needs.simple-extension-changes.outputs.changes) }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - uses: posit-dev/connect-gallery-action/build-extension@main
        with:
          extension-name: ${{ matrix.extension }}
          release: ${{ github.ref == 'refs/heads/main' }}

  # Runs Connect integration tests for each extension that was successfully
  # linted and packaged. Runs on both PRs and main.
  simple-extension-connect-integration-tests:
    needs: [simple-extension-changes, simple-extensions]
    if: ${{ needs.simple-extension-changes.outputs.changes != '[]' && needs.simple-extension-changes.outputs.changes != '' }}
    uses: ./.github/workflows/connect-integration-tests.yml
    with:
      extensions: ${{ needs.simple-extension-changes.outputs.changes }}
    secrets: inherit

  # Detects file changes for complex extension directories that require more
  # than the `simple-extensions` job offers.
  # For example, run a build script prior to packaging the extension TAR
  complex-extension-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      publisher-command-center-otel: ${{ steps.changes.outputs.publisher-command-center-otel }}
      # Adding a new extension with a complex build process?
      # Add a new line here with the name of the extension as the name of the
      # filter and the step output variable below
      # e.g. `extension-name: ${{ steps.changes.outputs.extension-name }}`
      # Be sure the extension name and directory name it is in are the same

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: changes
        with:
      #     # Adding a new extension that has a complex build process?
      #     # Add a new line here with the name of the extension and directory path
      #     # Be sure the extension name and directory have the same name
      #     # e.g. `extension-name: extensions/extension-name/**`
          filters: |
            publisher-command-center-otel: extensions/publisher-command-center-otel/**

  # Creates and releases the Publisher Command Center extension using a custom
  # workflow
  publisher-command-center-otel:
    needs: [complex-extension-changes]
    # Only runs if the `complex-extension-changes` job detects changes in the
    # publisher-command-center-otel extension directory
    if: ${{ needs.complex-extension-changes.outputs.publisher-command-center-otel == 'true' }}
    uses: ./.github/workflows/publisher-command-center-otel.yml
    secrets: inherit

  # All extensions have been linted, packaged, and released, if necessary
  # Regenerate extensions.json from manifests and GitHub Releases

  update-extension-list:
    runs-on: ubuntu-latest
    needs: [
      simple-extensions,
      publisher-command-center-otel,
      # Add complex extension job names here as needed
    ]
    if: ${{ always() && github.ref == 'refs/heads/main' }}

    steps:
      - name: Generate token for GitHub App
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 1129585
          private-key: ${{ secrets.POSIT_CONNECT_PROJECTS_PEM }}
          permission-contents: write

      # Checkout main to commit the updated extension list
      # reduces the chance of conflicts when updating the extension list with
      # multiple running workflows
      - uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ steps.generate-token.outputs.token }}

      - uses: posit-dev/connect-gallery-action@main
        with:
          extensions-dir: extensions
